name: Build Android APK

on:
    push:
        branches: [main, master]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Java 17
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "17"

            # Фіксуємо конкретну версію Flutter, сумісну з Flet 0.22.x
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.22.2"
                  channel: "stable"

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install uv
                  uv pip install --system "flet==0.22.0" yt-dlp

            - name: Build APK with Flet
              run: |
                  yes | flet build apk -vv

            - name: Upload APK Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: app-release
                  path: build/apk/*.apk
